name: expense_tracker
description: Simple expense tracker.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  provider: ^6.1.2

flutter:
  uses-material-design: true

